### ISSUE TITLE
Why UWP?

### ISSUE THREAD

**Issue by MrGold** [langboost/libaxolotl-uwp#15]
Hello,

Why this is a UWP project? This is a protocol implementation  that provides encryption , right? Why do we need to depend on Windows 10 and , UWP  SDK  to implement this protocol?  This protocol is also implemented in C/PHP/java ...etc  without such dependency. Why for C#  it requires Windows 10  and UWP SDK  on visual studio ? It is not possible to implement it  as common .NET 4.0 class library?

**Comment by jeff-r-skillrev** [comment]
It has more to do with how curve25519-uwp was implemented. It is a C++ WinRT component. Since that is a new Windows 10 technology, libaxolotl-uwp has to implicitly be UWP for now. I'm actually starting to port just a pure C# version of curve25519 to a portable class library, so that libraries such as this one can simply be PCL as well and work in traditional/classic .NET environments as well. I'll keep you posted on my progress. In the long-term, we may stick with the C++ WinRT dependency for Windows 10 (for performance reasons), but provide the PCL equivalent library for other implementations on other Windows platforms. There may or may not be a significant performance benefit to the C++ implementation. If there is no major benefit, maintaining one version of the library (C#) over two (C++ and C#) is obviously ideal.

**Comment by jeff-r-skillrev** [comment]
I have a newborn in the house, and haven't done much volunteer work the last two months. But when I get back around to it, I am working on the C# only version of curve25519 here: https://github.com/langboost/curve25519-pcl

**Comment by MrGold** [comment]
Thanks for the reply. Looking forward to pure C# implementation of the protocol.

**Comment by jeff-r-skillrev** [comment]
Just FYI, the pure C# version appears to more or less be working. I'm going to strengthen that assertion with more unit tests, but in the meantime, feel free to begin using it and submit any issues you find. Please report back on what platforms you use this with (classic .NET, windows phone, xbox, etc). I am depending on PCLCrypto, and I want to see if it truly supports all of the PCL compatible environments that I am expecting it to.
